let os = substitute(system("uname -s"), "\n", "", "")
let mapleader = ','

set nocompatible
filetype off


" vundle plugins {{
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#rc()

Plugin 'VundleVim/Vundle.vim'

" Filesytem Navigation {{
" http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/

" Project Drawer
" Plugin 'scrooloose/nerdtree'
" let NERDTreeChDirMode = 2
" let NERDTreeWinSize = 28
" let NERDTreeWinPos = "right"
" let NERDTreeShowBookmarks = 1
" let NERDTreeAutoDeleteBuffer = 1
" " Close vim if the only window open is NERDTree.
" autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
" map <silent> <Leader>nt :NERDTreeToggle<CR>
" let NERDTreeIgnore = [
" 		\ '^Session.vim$',
" 		\ '\.bin$',
" 		\ '\.out$',
" 		\ '\.elf$',
" 		\ '\.app$',
" 		\ '\.7z$',
" 		\ '\.gz$',
" 		\ '\.tar$',
" 		\ '\.zip$',
" 		\ '\.bz2$',
" 		\ '\.lzma$',
" 		\ '\.swp$',
" 		\ '\.swo$',
" 		\ '\~$',
" 		\ '\.o$',
" 		\ '\.so$',
" 		\ '\.d$',
" 		\ '\.6$',
" 		\ '\.beam$',
" 		\ '\.dylib$',
" 		\ '^cscope\..*',
" 		\ ]


" Split Explorer
" Plugin 'tpope/vim-vinegar'
" Plugin 'Shougo/vimfiler.vim'
" unstable and conflict with vim-vinegar
" let g:vimfiler_as_default_explorer = 1

""""""""""""""""""""
" netrw
""""""""""""""""""""
let g:netrw_liststyle = 3
let g:netrw_banner = 1
let g:netrw_keepdir = 1
let g:netrw_list_hide = '^\.,' . netrw_gitignore#Hide()
let g:netrw_hide = 1
let g:netrw_sort_options = "i"
let g:netrw_sort_sequence = '[\/]$,*,\.bak$,\.$,\.info$,\.swp$,\.obj$'
auto FileType netrw call s:setup_netrw_shortcuts()
function! s:setup_netrw_shortcuts()
    nmap <buffer> <nowait> q :bprevious<CR>
endfunction
if 1
else
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25
endif

" Filesystem Navigation }}

" Prompt for actions: creating new file or editing existing file(s)
Plugin 'EinfachTOll/DidYouMean'

Plugin 'a.vim'

Plugin 'L9'
Plugin 'FuzzyFinder'

Plugin 'tpope/vim-ragtag'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-dispatch'

Plugin 'wesQ3/vim-windowswap'

Plugin 'Shougo/vimproc.vim'
Plugin 'Shougo/unite.vim'
let g:unite_enable_start_insert = 1
nnoremap <C-p> :Unite file_rec/async<cr>

Plugin 'Shougo/unite-session'
let g:unite_source_session_enable_auto_save = 1
nnoremap <Leader>s :UniteSession

Plugin 'Shougo/unite-help'
Plugin 'ujihisa/unite-colorscheme'

Plugin 'Lokaltog/vim-easymotion'
Plugin 'scrooloose/syntastic'
let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = '-std=c++1y -stdlib=libc++'
Plugin 'jQuery'
Plugin 'gmarik/vim-markdown'
Plugin 'uarun/vim-protobuf'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'nosami/OmniSharpServer'


if has('python') || has('python3')
Plugin 'SirVer/ultisnips'
endif
Plugin 'honza/vim-snippets'

"Plugin 'Gundo'
"Plugin 'klen/python-mode'
"Plugin 'wesleyche/SrcExpl'
"Plugin 'wesleyche/Trinity'

Plugin 'tlib'
Plugin 'tComment'
nnoremap // :TComment<CR>
vnoremap // :TComment<CR>

"Plugin 'cscope.vim'
map <silent> <Leader>lo :!./cscope.sh<CR><CR>:cs reset<CR>
set cscopequickfix=""
set cscopetag		" force :tag and CTRL-] using :cstag
set cscopetagorder=0	" cscope database first, then tag files

"Plugin 'xolox/vim-reload'
"Plugin 'xolox/vim-misc'

"""""""""""""""""""""""""""
" colorscheme
"""""""""""""""""""""""""""
set t_Co=256
if has('gui_running')
	set background=light
    else
	set background=dark
endif

Plugin 'jonathanfilip/vim-lucius'

Plugin 'moria'
let moria_fontface = 'mixed'

Plugin 'altercation/vim-colors-solarized'
let g:solarized_visibility="high"
colorscheme solarized

Plugin 'tomasr/molokai'
let g:rehash256 = 1
let g:molokai_original = 1
" colorscheme molokai

if &term =~ '256color'
  " disable Background Color Erase (BCE) so that color schemes
  " render properly when inside 256-color tmux and GNU screen.
  " see also http://snk.tuxfamily.org/log/vim-256color-bce.html
  set t_ut=
endif

"" Make Vim recognize XTerm escape sequences for Page and Arrow
"" keys combined with modifiers such as Shift, Control, and Alt.
"" See http://www.reddit.com/r/vim/comments/1a29vk/_/c8tze8p
"if &term =~ '^screen'
"  " Page keys
"  " http://sourceforge.net/p/tmux/tmux-code/ci/master/tree/FAQ
"  execute "set t_kP=\e[5;*~"
"  execute "set t_kN=\e[6;*~"
"
"  " Arrow keys http://unix.stackexchange.com/a/34723
"  execute "set <xUp>=\e[1;*A"
"  execute "set <xDown>=\e[1;*B"
"  execute "set <xRight>=\e[1;*C"
"  execute "set <xLeft>=\e[1;*D"
"endif
"
"Plugin 'nacitar/terminalkeys.vim'

" Git
Plugin 'tpope/vim-fugitive'
" Plugin 'airblade/vim-gitgutter'

Plugin 'mhinz/vim-signify'
autocmd ColorScheme * highlight! link SignColumn LineNr

Plugin 'edkolev/tmuxline.vim'
let g:tmuxline_theme = 'airline'
let g:tmuxline_preset = 'tmux'

" statusline
Plugin 'bling/vim-airline'
set laststatus=2
let g:airline_detect_modified=1
let g:airline_detect_paste=1
let g:airline_detect_iminsert=0
let g:airline_powerline_fonts=1
let g:airline_extensions = [
			\ 'branch',
			\ 'quickfix',
			\ 'csv',
			\ 'whitespace',
			\ 'tmuxline',
			\ 'tagbar',
			\ 'windowswap',
			\ ]


" Plugin 'Valloric/YouCompleteMe'
" set completeopt=menuone
" let g:ycm_auto_trigger = 1
" let g:ycm_confirm_extra_conf = 0
" let g:ycm_add_preview_to_completeopt = 0
" let g:ycm_key_invoke_completion = '<C-x><C-y>'
" let g:ycm_show_diagnostics_ui = 0


" tagbar
Plugin 'majutsushi/tagbar'
if os == "FreeBSD"
let g:tagbar_ctags_bin = '/usr/local/bin/exctags'
endif
let g:tagbar_autoclose = 0
let g:tagbar_left = 1
let g:tagbar_sort = 0
let g:tagbar_width = 28
map <silent> <Leader>tb :TagbarToggle<CR>


" The Silver Searcher
Plugin 'rking/ag.vim'
autocmd QuickFixCmdPost grep cwindow
autocmd QuickFixCmdPost vimgrep cwindow

Plugin 'chrisbra/csv.vim'

Plugin 'cespare/vim-toml'
Plugin 'stephpy/vim-yaml'
Plugin 'saltstack/salt-vim'
Plugin 'markcornick/vim-vagrant'

" Go
Plugin 'nsf/gocode', {'rtp': 'vim/'}
Plugin 'fatih/vim-go'
let g:go_fmt_command = "goimports"
let g:go_fmt_experimental = 1
auto FileType go nmap gi <Plug>(go-info)
auto FileType go nmap gr <Plug>(go-rename)
auto FileType go nmap gt <Plug>(go-test)

let g:tagbar_type_go = {
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent',
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ }
\ }

" Swift
Plugin 'keith/swift.vim'


" Rust
Plugin 'wting/rust.vim'


" Scala
Plugin 'derekwyatt/vim-scala'
let g:tagbar_type_scala = {
    \ 'ctagstype' : 'scala',
    \ 'kinds'     : [
        \ 'p:packages:1',
        \ 'V:values',
        \ 'v:variables',
        \ 'T:types',
        \ 't:traits',
        \ 'o:objects',
        \ 'a:aclasses',
        \ 'c:classes',
        \ 'r:cclasses',
        \ 'm:methods'
    \ ]
\ }


" Haskell
let g:tagbar_type_haskell = {
    \ 'ctagsbin'  : 'hasktags',
    \ 'ctagsargs' : '-x -c -o-',
    \ 'kinds'     : [
        \  'm:modules:0:1',
        \  'd:data: 0:1',
        \  'd_gadt: data gadt:0:1',
        \  't:type names:0:1',
        \  'nt:new types:0:1',
        \  'c:classes:0:1',
        \  'cons:constructors:1:1',
        \  'c_gadt:constructor gadt:1:1',
        \  'c_a:constructor accessors:1:1',
        \  'ft:function types:1:1',
        \  'fi:function implementations:0:1',
        \  'o:others:0:1'
    \ ],
    \ 'sro'        : '.',
    \ 'kind2scope' : {
        \ 'm' : 'module',
        \ 'c' : 'class',
        \ 'd' : 'data',
        \ 't' : 'type'
    \ },
    \ 'scope2kind' : {
        \ 'module' : 'm',
        \ 'class'  : 'c',
        \ 'data'   : 'd',
        \ 'type'   : 't'
    \ }
\ }


" Erlang
Plugin 'jimenezrick/vimerl'

" vundle plugins }}


""""""""""""""""""""""""
" filetype
""""""""""""""""""""""""
filetype plugin indent on
syntax enable
set omnifunc=syntaxcomplete#Complete

set ruler number
set cmdheight=2
set incsearch hlsearch
" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set autoindent
set tabstop=8 softtabstop=0 shiftwidth=8 nosmarttab noexpandtab
autocmd FileType erlang,sh,lua,haskell,python,proto setlocal tabstop=4 softtabstop=0 shiftwidth=4 smarttab expandtab

map <silent> <Leader>tt :set tabstop=8 softtabstop=0 shiftwidth=8 nosmarttab noexpandtab<CR>
map <silent> <Leader>th :set tabstop=4 softtabstop=0 shiftwidth=4 nosmarttab noexpandtab<CR>
map <silent> <Leader>t4 :set tabstop=4 softtabstop=4 shiftwidth=4 smarttab expandtab<CR>
map <silent> <Leader>t2 :set tabstop=2 softtabstop=2 shiftwidth=2 smarttab expandtab<CR>

set history=50
set showcmd

set helplang=cn,en

"""""""""""""""""""""""""""
" file format
"""""""""""""""""""""""""""
set fileformats=unix,dos,mac fileformat=unix
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,big5,gb18030,euc-jp,euc-kr,latin1
set fileencoding=utf-8
set termencoding=utf-8
